# Generated by Django 3.0.6 on 2020-05-22 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_slot', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_booked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appointment_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_slot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
